from __future__ import annotations

import argparse
import json
from http.cookiejar import Cookie, CookieJar, MozillaCookieJar
from pathlib import Path
from typing import Iterable, Optional


NETSCAPE_HEADER = """# Netscape HTTP Cookie File
# This file was generated by Eppie. Do not edit.
"""


def filter_cookies(cookies: Iterable[dict], domain_suffix: str) -> list[dict]:
    filtered = []
    for cookie in cookies:
        domain = str(cookie.get("domain", "")).lower()
        if domain.endswith(domain_suffix):
            filtered.append(cookie)
    return filtered


def _bool_flag(value: bool) -> str:
    return "TRUE" if value else "FALSE"


def cookie_to_netscape_line(cookie: dict) -> str:
    domain = str(cookie.get("domain", ""))
    include_subdomains = domain.startswith(".")
    path = str(cookie.get("path", "/"))
    secure = bool(cookie.get("secure", False))
    expires = int(cookie.get("expires") or 0)
    name = str(cookie.get("name", ""))
    value = str(cookie.get("value", ""))
    return "\t".join(
        [
            domain,
            _bool_flag(include_subdomains),
            path,
            _bool_flag(secure),
            str(expires),
            name,
            value,
        ]
    )


def write_netscape_cookiejar(cookies: Iterable[dict], output_path: Path, domain_suffix: str) -> int:
    filtered = filter_cookies(cookies, domain_suffix)
    lines = [NETSCAPE_HEADER.strip()] + [cookie_to_netscape_line(c) for c in filtered]
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return len(filtered)


def _cookie_from_json(cookie: dict) -> Cookie:
    domain = str(cookie.get("domain", ""))
    domain_initial_dot = domain.startswith(".")
    return Cookie(
        version=0,
        name=str(cookie.get("name", "")),
        value=str(cookie.get("value", "")),
        port=None,
        port_specified=False,
        domain=domain,
        domain_specified=bool(domain),
        domain_initial_dot=domain_initial_dot,
        path=str(cookie.get("path", "/")),
        path_specified=True,
        secure=bool(cookie.get("secure", False)),
        expires=int(cookie.get("expires") or 0) or None,
        discard=False,
        comment=None,
        comment_url=None,
        rest={},
        rfc2109=False,
    )


def cookiejar_from_json(cookies: Iterable[dict], domain_suffix: str) -> CookieJar:
    jar = CookieJar()
    for cookie in filter_cookies(cookies, domain_suffix):
        jar.set_cookie(_cookie_from_json(cookie))
    return jar


def load_cookie_jar_from_path(path: Path, domain_suffix: str) -> Optional[CookieJar]:
    if not path.exists():
        return None
    if path.suffix.lower() == ".json":
        cookies = json.loads(path.read_text(encoding="utf-8"))
        if isinstance(cookies, dict):
            cookies = cookies.get("cookies", [])
        return cookiejar_from_json(cookies, domain_suffix)
    try:
        cookies = json.loads(path.read_text(encoding="utf-8"))
        if isinstance(cookies, list):
            return cookiejar_from_json(cookies, domain_suffix)
    except json.JSONDecodeError:
        pass
    jar = MozillaCookieJar()
    jar.load(str(path), ignore_discard=True, ignore_expires=True)
    return jar


def verify_urls(cookie_jar: CookieJar, urls: Iterable[str]) -> list[tuple[str, int]]:
    import requests

    session = requests.Session()
    session.cookies = cookie_jar
    results = []
    for url in urls:
        try:
            resp = session.get(url, timeout=20, allow_redirects=True)
            results.append((url, resp.status_code))
        except Exception:
            results.append((url, 0))
    return results


def main() -> None:
    parser = argparse.ArgumentParser(description="Write Netscape cookie jar.")
    parser.add_argument("--input", help="Path to JSON cookie list")
    parser.add_argument("--output", help="Path to Netscape cookie jar")
    parser.add_argument("--domain", default="justice.gov", help="Domain suffix to include")
    parser.add_argument("--verify", action="store_true", help="Verify URLs with cookie jar")
    parser.add_argument("--jar", help="Path to cookie jar (json or netscape)")
    parser.add_argument("--urls", nargs="*", default=[], help="URLs to verify")
    args = parser.parse_args()

    if args.verify:
        if not args.jar:
            raise SystemExit("--jar is required for verification")
        jar = load_cookie_jar_from_path(Path(args.jar), args.domain)
        if jar is None:
            raise SystemExit("cookie jar not found")
        results = verify_urls(jar, args.urls)
        for url, status in results:
            print(f"[auth] verify {url} status={status}")
        return

    if not args.input or not args.output:
        raise SystemExit("--input and --output are required")

    cookies = json.loads(Path(args.input).read_text(encoding="utf-8"))
    output_path = Path(args.output)
    count = write_netscape_cookiejar(cookies, output_path, args.domain)
    print(f"[auth] wrote {count} cookies to {output_path}")


if __name__ == "__main__":
    main()
