from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Iterable


NETSCAPE_HEADER = """# Netscape HTTP Cookie File
# This file was generated by Eppie. Do not edit.
"""


def filter_cookies(cookies: Iterable[dict], domain_suffix: str) -> list[dict]:
    filtered = []
    for cookie in cookies:
        domain = str(cookie.get("domain", "")).lower()
        if domain.endswith(domain_suffix):
            filtered.append(cookie)
    return filtered


def _bool_flag(value: bool) -> str:
    return "TRUE" if value else "FALSE"


def cookie_to_netscape_line(cookie: dict) -> str:
    domain = str(cookie.get("domain", ""))
    include_subdomains = domain.startswith(".")
    path = str(cookie.get("path", "/"))
    secure = bool(cookie.get("secure", False))
    expires = int(cookie.get("expires") or 0)
    name = str(cookie.get("name", ""))
    value = str(cookie.get("value", ""))
    return "\t".join(
        [
            domain,
            _bool_flag(include_subdomains),
            path,
            _bool_flag(secure),
            str(expires),
            name,
            value,
        ]
    )


def write_netscape_cookiejar(cookies: Iterable[dict], output_path: Path, domain_suffix: str) -> int:
    filtered = filter_cookies(cookies, domain_suffix)
    lines = [NETSCAPE_HEADER.strip()] + [cookie_to_netscape_line(c) for c in filtered]
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return len(filtered)


def main() -> None:
    parser = argparse.ArgumentParser(description="Write Netscape cookie jar.")
    parser.add_argument("--input", required=True, help="Path to JSON cookie list")
    parser.add_argument("--output", required=True, help="Path to Netscape cookie jar")
    parser.add_argument("--domain", default="justice.gov", help="Domain suffix to include")
    args = parser.parse_args()

    cookies = json.loads(Path(args.input).read_text(encoding="utf-8"))
    output_path = Path(args.output)
    count = write_netscape_cookiejar(cookies, output_path, args.domain)
    print(f"[auth] wrote {count} cookies to {output_path}")


if __name__ == "__main__":
    main()
